<a href="https://colab.research.google.com/github/neeyatiraisinghani/neeyati/blob/main/array23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

import sklearn as sk
from sklearn.model_selection import train_test_split

# importing data
home=np.array([1000,2000,3000,4000,5000,6000,7000,8000,9000,10000])

price=np.array([100,200,300,400,500,600,700,800,900,1000])

# head of the data
print(home)
print(price)


# using the train test split function
home_train, home_test, price_train, price_test = train_test_split(home,price, random_state=41,test_size=0.5, shuffle=True)

# printing out train and test sets

print("home_train :",home_train)

print("home_test : ",home_test)

print('price_train : ',price_train)

print("price_test : ",price_test)


[ 1000  2000  3000  4000  5000  6000  7000  8000  9000 10000]
[ 100  200  300  400  500  600  700  800  900 1000]
home_train : [10000  3000  5000  4000  1000]
home_test :  [6000 7000 8000 9000 2000]
price_train :  [1000  300  500  400  100]
price_test :  [600 700 800 900 200]


In [19]:
import numpy as np

import sklearn as sk

from sklearn.model_selection import train_test_split



from sklearn.linear_model import LinearRegression
home=np.array([100, 200, 300, 400, 500])

price = np.array([1500, 2500, 3500,4500, 5500])

print(home)

print(price)

home_train, home_test, price_train, price_test = train_test_split( home, price, random_state=41, test_size=0.5,shuffle=True)

print("home_train:",home_train)

print("home_test:", home_test)

print("price_train:",price_train)

print("price_test:",price_test)

home_train=home_train.reshape(-1,1)

home_test=home_test.reshape(-1,1)

price_train=price_train.reshape(-1,1)

price_test-price_test.reshape(-1,1)

regr= LinearRegression()

regr.fit(home_train, price_train)

print(regr.score(home_test,price_test))
print(regr.predict(home_test))

[100 200 300 400 500]
[1500 2500 3500 4500 5500]
home_train: [400 100]
home_test: [200 300 500]
price_train: [4500 1500]
price_test: [2500 3500 5500]
1.0
[[2500.]
 [3500.]
 [5500.]]
